version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  latest-chrome:
    docker:
      - image: "cypress/browsers:node14.7.0-chrome84"
workflows:
  build:
    jobs:
      - hold:
          type: approval
      - cypress/run:
          requires:
            - hold
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/vex/*"
      - cypress/run:
          requires:
            - hold
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/microsites/*"
      - cypress/run:
          requires:
            - hold
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/common/*\
                cypress/integration/explore/*\
                cypress/integration/recommend/*\
                cypress/integration/target/*"