version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  latest-chrome:
    docker:
      - image: "cypress/browsers:node14.7.0-chrome84"
workflows:
  staging-tues-thurs:
    triggers:
      - schedule:
          cron: "0 5 * * 2,4"
          filters:
            branches:
              only:
                - develop
    jobs:
      - cypress/run:
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/vex/*"
      - cypress/run:
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/microsites/*"
      - cypress/run:
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/common/*,\
                cypress/integration/explore/*,\
                cypress/integration/recommend/*,\
                cypress/integration/target/*"
  qa-sat-mon:
    triggers:
      - schedule:
          cron: "0 5 * * 1,6"
          filters:
            branches:
              only:
                - qa
    jobs:
      - cypress/run:
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/vex/*"
      - cypress/run:
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/microsites/*"
      - cypress/run:
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/common/*,\
                cypress/integration/explore/*,\
                cypress/integration/recommend/*,\
                cypress/integration/target/*"