version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  latest-chrome:
    docker:
      - image: "cypress/browsers:node14.7.0-chrome84"
    resource_class: large
steps:
  - run:
    no_output_timeout: 30m   
workflows:
  staging-tues-thurs:
    triggers:
      - schedule:
          # cron: "0 5 * * 2,4"
          filters:
            branches:
              only:
                - develop
    jobs:
      - cypress/run:
          name: VEX
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/vex/*"
      - cypress/run:
          name: Microsites
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/microsites/*"
      - cypress/run:
          name: Target Recommend Explore Common
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/common/*,\
            cypress/integration/contentIntelligence/*,\ 
            cypress/integration/explore/*,\
            cypress/integration/recommend/*,\
            cypress/integration/settings/*,\ 
            cypress/integration/target/*"
  staging-governance-tues-thurs:
    triggers:
      - schedule:
          # cron: "0 3 * * 2,4"
          filters:
            branches:
              only:
                - develop
    jobs:
      - cypress/run:
          name: Governance
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/userManagement/*"
  qa-sat-mon:
    triggers:
      - schedule:
          # cron: "0 5 * * 1,6"
          cron: "0 5 * * 4,6"
          filters:
            branches:
              only:
                - qa
    jobs:
      - cypress/run:
          name: VEX
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/vex/*"
      - cypress/run:
          name: Microsites
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/microsites/*"
      - cypress/run:
          name: Target Recommend Explore Common
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/common/*,\
            cypress/integration/contentIntelligence/*,\
            cypress/integration/explore/*,\
            cypress/integration/recommend/*,\
            cypress/integration/settings/*,\ 
            cypress/integration/target/*"
  qa-governance-sat-mon:
    triggers:
      - schedule:
          # cron: "0 3 * * 1,6"
          cron: "0 3 * * 4,6"
          filters:
            branches:
              only:
                - qa
    jobs:
      - cypress/run:
          name: Governance
          executor: latest-chrome
          browser: chrome
          spec: "cypress/integration/userManagement/*"
